# Generated by Django 4.1.5 on 2023-01-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_variation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"verbose_name": "Caracteristique", "verbose_name_plural": "Caracteristiques"},
        ),
    ]
