# Generated by Django 4.1.5 on 2023-01-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_variation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
