# Generated by Django 4.1.5 on 2023-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
        ("products", "0006_remove_categorie_active_categorie_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(related_name="upload", to="upload.image", verbose_name="article image"),
        ),
    ]
