# Generated by Django 4.1.5 on 2023-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name="Prix"),
        ),
    ]
