# Generated by Django 4.1.5 on 2023-01-26 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.apps.accounts.models
import phonenumber_field.modelfields
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Masculin", "Mr"), ("Feminin", "Mme")],
                        max_length=20,
                        null=True,
                        verbose_name="Genre",
                    ),
                ),
                ("lastname", models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de famille")),
                ("firstname", models.CharField(blank=True, max_length=100, null=True, verbose_name="Prénom")),
                ("birth_date", models.DateField(verbose_name="Date de naissance")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name="Téléphone"
                    ),
                ),
                ("bio", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "avatar",
                    versatileimagefield.fields.VersatileImageField(
                        height_field="height",
                        upload_to=ecommerce.apps.accounts.models.upload_image_path,
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "png"])],
                        verbose_name="Photo de profil",
                        width_field="width",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Adresse email",
                    ),
                ),
            ],
        ),
    ]
