# Generated by Django 4.1.5 on 2023-01-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0007_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_id", models.CharField(blank=True, max_length=250)),
                ("date_added", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(verbose_name="quantité")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cart2", verbose_name="panier"
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.product", verbose_name="articles"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name="Prix Hors Taxe"),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name="Prix total TTC "),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("update", models.DateTimeField(auto_now=True, verbose_name="Mis à jour")),
                ("products", models.ManyToManyField(blank=True, to="products.product", verbose_name="Articles")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Paniers",
            },
        ),
    ]
